### ISSUE TITLE
openapi-to-graphql-cli doesn't work

### ISSUE THREAD

**Issue by francislagares** [IBM/openapi-to-graphql#418]
**Describe the bug**
openapi-to-graphql-cli not working.

**To Reproduce**
1. npm i -g openapi-to-graphql-cli
2.  openapi-to-graphql --version

**Expected behavior**
Display openapi-to-graphql version number

This is what I get => 

3. .nvm/versions/node/v16.5.0/bin/openapi-to-graphql: 1: use strict: not found
4. .nvm/versions/node/v16.5.0/bin/openapi-to-graphql: 3: Syntax error: "(" unexpected

**Additional context**
Cannot create GraphQL Schema with Loopback4 npx openapi-to-graphql-cli --port=3001 http://localhost:3000/openapi.json

**Comment by leemcmullen** [comment]
Seems to be an issue with version 2.5.1.

I rolled back to 1.5.0 and it worked for me.

**Comment by francislagares** [comment]
Thanks I could make it run as Patmessina but
I'm not using openapi-to-graphql-cli anymore, nested queries don't work neither.

**Comment by lewismc** [comment]
Yes the issue is with the shebang line not being present in the `openapi-to-graphql` script
Add the following
```node
#!/usr/bin/env node
``` 
to `/path/to/.nvm/versions/node/${version}/bin/openapi-to-graphql` and it will work.

**Comment by Alan-Cha** [comment]
Sorry for the radio silence. I am finally back to help maintain the project. Thanks to @MarcoDaniels, this issue should now be resolved with version 2.5.2.

**Comment by afisher88** [comment]
I'm still having this problem in version 2.5.2 of CLI

**In oh-my-zsh**
`openapi-to-graphql --version`

**Output (truncated)**
`line 1: use strict: command not found`
`line 3: syntax error near unexpected token 'ex'`
`line 3: 'function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }'`
